#!/usr/bin/env bash

### Helpers begin
check_deps() {
    local missing
    for d in "${deps[@]}"; do
        if [[ -z $(command -v "$d") ]]; then
            # Force absolute path
            if [[ ! -f "/$d" ]]; then
                err "$d was not found"
                missing="true"
            fi
        fi
    done; unset d
    [[ -z $missing ]] || exit 128
}
err() { echo -e "${color:+\e[31m}[!] $*\e[0m"; }
errx() { err "${*:2}"; exit "$1"; }
good() { echo -e "${color:+\e[32m}[+] $*\e[0m"; }
info() { echo -e "${color:+\e[37m}[*] $*\e[0m"; }
long_opt() {
    local arg shift="0"
    case "$1" in
        "--"*"="*) arg="${1#*=}"; [[ -n $arg ]] || usage 127 ;;
        *) shift="1"; shift; [[ $# -gt 0 ]] || usage 127; arg="$1" ;;
    esac
    echo "$arg"
    return $shift
}
subinfo() { echo -e "${color:+\e[36m}[=] $*\e[0m"; }
warn() { echo -e "${color:+\e[33m}[-] $*\e[0m"; }
### Helpers end

default_vpn() {
    local ret="$(json_get "default_vpn")"
    echo "${ret:-pia}"
}

json_get() {
    local config="${2:-$conf}"
    if [[ -z $config ]] || [[ ! -f "$config" ]]; then
        return
    fi
    jq -cMrS ".$1" "$config" | sed -r "s/^null$//g"
}

usage() {
    # stop             Disconnect from VPN
    cat <<EOF
Usage: ${0##*/} [OPTIONS] <action> [vpn]

This is a wrapper script for other vpn scripts. Any OpenVPN provider
should be supported.

Actions:
    help             Display this help message
    list             List the vpn options
    start            Connect to VPN

Options:
    -g, --gw=GW      Use the specified gateway
    -h, --help       Display this help message
    --no-color       Disable colorized output
    -r, --random     Use random VPN gateway
    -v, --vpn=VPN    Use the specified VPN (default: $(default_vpn))

EOF
    exit "$1"
}

declare -a args deps
unset action clr conf help gw rand vpn
color="true"
confdir="$HOME/.config/vpn"
[[ ! -f "$confdir/vpn.conf" ]] || conf="$confdir/vpn.conf"
deps+=("jq")
deps+=("openvpn")

# Check for missing dependencies
check_deps

# Parse command line options
while [[ $# -gt 0 ]]; do
    case "$1" in
        "--") shift && args+=("$@") && break ;;
        "-g"|"--gw"*) gw="$(long_opt "$@")" || shift ;;
        "-h"|"--help") help="true" ;;
        "--no-color") clr="--nocolor"; unset color ;;
        "-r"|"--random") rand="--random" ;;
        "-v"|"--vpn"*) vpn="$(long_opt "$@")" || shift ;;
        *) args+=("$1") ;;
    esac
    shift
done
[[ ${#args[@]} -eq 0 ]] || set -- "${args[@]}"

# Check for valid params
[[ -z $help ]] || usage 0
[[ $# -gt 0 ]] || usage 1

action="$1"
[[ -n $vpn ]] || [[ $# -eq 1 ]] || vpn="$2"

providers="INSTALL_DIR/providers"
[[ $0 != "./vpn" ]] || providers="providers"

(
    cd $providers

    case "$action" in
        "start") [[ -n $vpn ]] || vpn="$(default_vpn)" ;;
        # "start"|"stop") [[ -n $vpn ]] || vpn="$(default_vpn)" ;;
    esac
    if [[ -n $vpn ]]; then
        [[ -d "$vpn" ]] || errx 2 "$vpn doesn't exist"
        cd "$vpn"
        case "$(json_get "type" vpn.conf)" in
            "openconnect") script="./vpn.sh" ;;
            "openvpn") script="../../openvpn.sh" ;;
            *) errx 3 "Provider not configured" ;;
        esac
    fi

    case "$action" in
        "help")
            if [[ -n $vpn ]]; then
                $script -h $clr
            else
                usage 0
            fi
            ;;
        "list")
            if [[ -n $vpn ]]; then
                $script $clr list
            else
                find . -maxdepth 1 -mindepth 1 \
                    \( -type d -o -type l \) | sed "s#./##g" | sort
            fi
            ;;
        "start") $script ${gw:+-g $gw} $clr $rand "$action" ;;
        # "start"|"stop") $script ${gw:+-g $gw} $clr $rand "$action" ;;
        *) usage 4
    esac
)
